name: Release

on:
  push:
    branches: [master]
    tags:
      - '*'

jobs:
  macOS-release:
    runs-on: [macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"

      - name: Setup build environment
        run: |
          pip install -r requirements.txt
          brew install expect
          echo "::set-env name=VERSION::$(cat version)"

      - name: Login to FBS
        run: /usr/bin/expect .github/scripts/mac/login.sh
        env:
          FBS_USER: ${{ secrets.FBS_USER }}
          FBS_PASS: ${{ secrets.FBS_PASS }}
          GPG_PASS: ${{ secrets.GPG_PASS }}

      - name: Build Installer
        run: /usr/bin/expect .github/scripts/mac/release.sh

      - name: Export setup dmg as .zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: macOS dmg
          path: target/HandWriter.dmg

  Windows-release:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"

      - name: Setup build environment
        run: |
          pip install pywin32
          pip install -r requirements.txt
          echo "::set-env name=VERSION::$(type version)"
    
      - name: Release
        run: |
          python .\.github\scripts\windows\release.py

      - name: Export installer as .zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: Windows Installer
          path: target/HandWriterSetup.exe

  Debian-release:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"

      - name: Setup release environment
        run:  | 
          sudo apt-get install expect
          pip install fbs
          echo "::set-env name=VERSION::$(cat version)"
          # Login with appropriate credentials
          /usr/bin/expect .github/scripts/linux-base/login.sh 
        env:
          FBS_USER: ${{ secrets.FBS_USER }}
          FBS_PASS: ${{ secrets.FBS_PASS }}
          GPG_PASS: ${{ secrets.GPG_PASS }}
          EMAIL: ${{ secrets.EMAIL }}
          NAME: ${{ secrets.NAME }}

      - name: Build VM
        run: fbs buildvm ubuntu

      - name: Release
        run: |
          chmod a+x .github/scripts/ubuntu/release.sh
          .github/scripts/ubuntu/release.sh

  Arch-Release:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"

      - name: Setup release environment
        run:  | 
          sudo apt-get install expect
          pip install fbs
          echo "::set-env name=VERSION::$(cat version)"
          # Login with appropriate credentials
          /usr/bin/expect .github/scripts/linux-base/login.sh 
        env:
          FBS_USER: ${{ secrets.FBS_USER }}
          FBS_PASS: ${{ secrets.FBS_PASS }}
          GPG_PASS: ${{ secrets.GPG_PASS }}
          EMAIL: ${{ secrets.EMAIL }}
          NAME: ${{ secrets.NAME }}

      - name: Build VM
        run: fbs buildvm arch

      - name: Release
        run: |
          chmod a+x .github/scripts/arch/release.sh
          .github/scripts/arch/release.sh

  Fedora-Release:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"

      - name: Setup release environment
        run:  | 
          sudo apt-get install expect
          pip install fbs
          echo "::set-env name=VERSION::$(cat version)"
          # Login with appropriate credentials
          /usr/bin/expect .github/scripts/linux-base/login.sh 
        env:
          FBS_USER: ${{ secrets.FBS_USER }}
          FBS_PASS: ${{ secrets.FBS_PASS }}
          GPG_PASS: ${{ secrets.GPG_PASS }}
          EMAIL: ${{ secrets.EMAIL }}
          NAME: ${{ secrets.NAME }}

      - name: Build VM
        run: fbs buildvm fedora

      - name: Release
        run: |
          chmod a+x .github/scripts/fedora/release.sh
          .github/scripts/fedora/release.sh

  Publish:
    runs-on: [ubuntu-latest]
    needs: [macOS-release, Windows-release]

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/download-artifact@v2
        with:
          name: macOS dmg

      - uses: actions/download-artifact@v2
        with:
          name: Windows Installer

      - name: Setup release environment
        run: |
          echo "::set-env name=VERSION::$(cat version)"
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          
      - name: Release
        uses: ncipollo/release-action@v1
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: ${{ env.VERSION }}
          commit: master 
          artifacts: "macOS dmg, Windows Installer"

      - name: Modify website pages
        run: |
          # Cloning the website repo
          git clone git@github.com:GDGVIT/handwriter-website.git
          cd handwriter-website
          sed 's/{VERSION}/'"${{ env.VERSION }}"'/' templates/home.md > content/installer/home.md
          
      - name: Push changes to website repo
        run: |
          cd handwriter-website
          git add content/installer/
          git commit --allow-empty -m "Automated website build for upstream package update"
          git push --force