name: Release

on:
  push:
    branches: [ master ]

jobs:
  macOS-release:
    runs-on: [macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'

      - name: Setup release environment
        run: |
          pip install -r requirements.txt
          brew install expect
          . version

      - name: Login
        run: /usr/bin/expect .github/scripts/mac/login.sh
        env:
          FBS_USER: ${{ secrets.FBS_USER }}
          FBS_PASS: ${{ secrets.FBS_PASS }}
          GPG_PASS: ${{ secrets.GPG_PASS }}
          
      - name: Release
        run: yes $VERSION | fbs release

      - name: Check release
        run: |
          ls
          ls target

      - name: Export .zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: macOS dmg
          path: macos
